version: "3.2"
services:
  web:
    build: ./php/build/dev
    container_name: web    
    volumes:
      - ./src:/var/www/html
      - ./certs/dev:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    env_file:
    - .env
